# Análise de Dados do Banco Fácil 🏦

In [1]:
import pandas as pd
import numpy as np

## 1. Os Dados

Os dados são referentes a transações de cliente dos Banco Fácil, composta por duas tabelas - uma de clientes e uma de transações.

In [2]:
# Base de transações
transacoes = pd.DataFrame({
    'id_cliente': [1, 2, 1, 3, 2, 1, 3, 2],
    'tipo':       ['Crédito', 'Débito', 'Débito', 'Crédito', 'Crédito', 'Débito', 'Débito', 'Crédito'],
    'categoria':  ['Salário', 'Alimentação', 'Transporte', 'Salário', 'Lazer', 'Alimentação', 'Transporte', 'Salário'],
    'valor':      [3200.0, 150.0, None, 4500.0, 200.0, 80.0, None, 2800.0],
    'canal':      ['App', 'Agência', 'App', 'Internet Banking', 'App', 'Agência', 'App', 'Internet Banking']
})

# Base de cadastro de clientes
clientes = pd.DataFrame({
    'id_cliente': [1, 2, 3, 4],
    'nome':       ['Ana', 'Bruno', 'Carlos', 'Diana'],
    'estado':     ['SP', 'RJ', 'MG', 'SP'],
    'perfil':     ['Premium', 'Básico', 'Intermediário', 'Básico']
})

## 2. Conhecendo os Dados

### --- Tabela de Clientes ---

In [3]:
# Tamanho da Tabela
print('O Tamanho da Tabela de clientes é: ', clientes.shape)
print('*'*20)

# Tipos de Dados
print('Os tipos de dados presentes na tabela de clientes são: \n', clientes.dtypes)
print('*'*20)

# Formato da Tabela
display(clientes.head())
print('*'*20)

# Células Vazias
print('Número de células vazias em cada coluna: \n', clientes.isna().sum())

O Tamanho da Tabela de clientes é:  (4, 4)
********************
Os tipos de dados presentes na tabela de clientes são:
 id_cliente     int64
nome          object
estado        object
perfil        object
dtype: object
********************

   id_cliente    nome estado         perfil
0           1     Ana     SP        Premium
1           2   Bruno     RJ         Básico
2           3  Carlos     MG  Intermediário
3           4   Diana     SP         Básico

********************
Número de células vazias em cada coluna:
 id_cliente    0
nome          0
estado        0
perfil        0
dtype: int64

### --- Tabela de Transações ---

In [4]:
# Tamanho da Tabela
print('O Tamanho da Tabela de transações é: ', transacoes.shape)
print('*'*20)

# Tipos de Dados
print('Os tipos de dados presentes na tabela de transações são: \n', transacoes.dtypes)
print('*'*20)

# Formato da Tabela
display(transacoes.head(8))
print('*'*20)

# Campos nulos
print('Número de campos nulos em cada coluna: \n', transacoes.isna().sum())

O Tamanho da Tabela de transações é:  (8, 5)
********************
Os tipos de dados presentes na tabela de transações são:
 id_cliente      int64
tipo           object
categoria      object
valor         float64
canal          object
dtype: object
********************

   id_cliente     tipo    categoria   valor             canal
0           1  Crédito      Salário  3200.0               App
1           2   Débito  Alimentação   150.0           Agência
2           1   Débito   Transporte     NaN               App
3           3  Crédito      Salário  4500.0  Internet Banking
4           2  Crédito        Lazer   200.0               App
5           1   Débito  Alimentação    80.0           Agência
6           3   Débito   Transporte     NaN               App
7           2  Crédito      Salário  2800.0  Internet Banking

********************
Número de campos nulos em cada coluna:
 id_cliente    0
tipo          0
categoria     0
valor         2
canal         0
dtype: int64

### --- Análise ---

In [5]:
print(f'O Banco Fácil possui: {len(clientes)} clientes cadastrados.\n')
print(f'O Banco Fácil registrou: {len(transacoes)} transações no período.\n')
print(f'Existem {transacoes['valor'].isna().sum()} transações sem valor correspondente.\n')

O Banco Fácil possui: 4 clientes cadastrados.

O Banco Fácil registrou: 8 transações no período.

Existem 2 transações sem valor correspondente.

## 3. Limpeza dos Dados

In [6]:
# Preenchendo os campos nulos com a mediana dos valores de transação

transacoes['valor'] = transacoes['valor'].fillna(transacoes['valor'].median())
display(transacoes)

# Confirmando se há campos nulos
print('Número de campos nulos em cada coluna: \n', transacoes.isna().sum())
print(f'\nExistem {transacoes['valor'].isna().sum()} transações sem valor correspondente.\n')

   id_cliente     tipo    categoria   valor             canal
0           1  Crédito      Salário  3200.0               App
1           2   Débito  Alimentação   150.0           Agência
2           1   Débito   Transporte  1500.0               App
3           3  Crédito      Salário  4500.0  Internet Banking
4           2  Crédito        Lazer   200.0               App
5           1   Débito  Alimentação    80.0           Agência
6           3   Débito   Transporte  1500.0               App
7           2  Crédito      Salário  2800.0  Internet Banking

Número de campos nulos em cada coluna:
 id_cliente    0
tipo          0
categoria     0
valor         0
canal         0
dtype: int64

Existem 0 transações sem valor correspondente.

## 4. Cálculos sobre valores

In [7]:
# Criando array numpy da coluna valor
transacoes_valores = np.array(transacoes['valor'])
print(transacoes_valores)
print(type(transacoes_valores))

[3200.  150. 1500. 4500.  200.   80. 1500. 2800.]
<class 'numpy.ndarray'>

In [8]:
# Total de Transações
print(f'O Valor total de transações no período foi de: R$ {transacoes_valores.sum()}\n')
# Valor Médio das Transações
print(f'O Valor médio das transações no período foi de: R$ {transacoes_valores.mean()}\n')
# Valor mínimo de Transação
print(f'O Valor mínimo das transações no período foi de: R$ {transacoes_valores.min()}\n')
# Valor Máximo de Transação
print(f'O Valor máximo das transações no período foi de: R$ {transacoes_valores.max()}\n')

O Valor total de transações no período foi de: R$ 13930.0

O Valor médio das transações no período foi de: R$ 1741.25

O Valor mínimo das transações no período foi de: R$ 80.0

O Valor máximo das transações no período foi de: R$ 4500.0

## 5. Relacionamento entre as Bases

In [9]:
# Fazendo um Join com inner
df_inner = pd.merge(
    transacoes,
    clientes,
    on='id_cliente',
    how='inner'
)
display(df_inner)

# Fazendo um Join com left partindo da tabela clientes

df_left = pd.merge(
    clientes,
    transacoes,
    on='id_cliente',
    how='left'
)
display(df_left)

,id_cliente,tipo,categoria,valor,canal,nome,estado,perfil
0,1,Crédito,Salário,3200.0,App,Ana,SP,Premium
1,2,Débito,Alimentação,150.0,Agência,Bruno,RJ,Básico
2,1,Débito,Transporte,1500.0,App,Ana,SP,Premium
3,3,Crédito,Salário,4500.0,Internet Banking,Carlos,MG,Intermediário
4,2,Crédito,Lazer,200.0,App,Bruno,RJ,Básico
5,1,Débito,Alimentação,80.0,Agência,Ana,SP,Premium
6,3,Débito,Transporte,1500.0,App,Carlos,MG,Intermediário
7,2,Crédito,Salário,2800.0,Internet Banking,Bruno,RJ,Básico

,id_cliente,nome,estado,perfil,tipo,categoria,valor,canal
0,1,Ana,SP,Premium,Crédito,Salário,3200.0,App
1,1,Ana,SP,Premium,Débito,Transporte,1500.0,App
2,1,Ana,SP,Premium,Débito,Alimentação,80.0,Agência
3,2,Bruno,RJ,Básico,Débito,Alimentação,150.0,Agência
4,2,Bruno,RJ,Básico,Crédito,Lazer,200.0,App
5,2,Bruno,RJ,Básico,Crédito,Salário,2800.0,Internet Banking
6,3,Carlos,MG,Intermediário,Crédito,Salário,4500.0,Internet Banking
7,3,Carlos,MG,Intermediário,Débito,Transporte,1500.0,App
8,4,Diana,SP,Básico,NaN,NaN,NaN,NaN

In [10]:
# Comparando o shape dos dois DataFrames
print(
    f'O DataFrame feito pelo inner partindo das transações tem: {df_inner.shape[0]} linhas e {df_inner.shape[1]} colunas\n'
    f'Enquanto o DataFrame feito pelo left partindo da tabela clientes tem: {df_left.shape[0]} linhas e {df_left.shape[1]} colunas'
)

O DataFrame feito pelo inner partindo das transações tem: 8 linhas e 8 colunas
Enquanto o DataFrame feito pelo left partindo da tabela clientes tem: 9 linhas e 8 colunas

In [11]:
# Investigando os campos nulos do df_left

display(df_left.loc[df_left['valor'].isna()])

   id_cliente   nome estado  perfil tipo categoria  valor canal
8           4  Diana     SP  Básico  NaN       NaN    NaN   NaN

### --- Análise ---

O DataFrame gerado pelo `pd.merge()` a partir da tabela clientes possui uma linha a mais.

A cliente **Diana** que encontra-se cadastrada na tabela de clientes, não realizou nenhuma transação no período. 

Neste modo `left` do `pd.merge()` o pandas relaciona as transações com os clientes, preenchendo com campos nulos clientes que não realizaram transações no período.

## 6. Analise do Perfil

In [12]:
# Analisando o perfil pela soma e média de transações dos clientes

perfil = df_inner.groupby('perfil').agg(
    soma   =   ('valor', 'sum'),
    media   =   ('valor', 'mean')
).round(2).reset_index()

display(perfil)

          perfil    soma    media
0         Básico  3150.0  1050.00
1  Intermediário  6000.0  3000.00
2        Premium  4780.0  1593.33

### --- Análise ---

In [13]:
# Perfil com maior média de transações
print('O Perfil que teve a maior média de transações foi: ', 
      perfil.loc[perfil['media'] == perfil['media'].max(), 'perfil'].values[0],
      ', com R$',
      perfil['media'].max().round(2),
      'transações.'
      )

O Perfil que teve a maior média de transações foi:  Intermediário , com R$ 3000.0 transações.

## 7. Arquivo CSV

In [14]:
# Criando o arquivo .csv para df_inner

df_inner.to_csv('base_combinada.csv', index=False)

In [15]:
# Lendo arquivo .csv 

df_combinado = pd.read_csv('base_combinada.csv', sep= ',', encoding='UTF-8')
display(df_combinado)

,id_cliente,tipo,categoria,valor,canal,nome,estado,perfil
0,1,Crédito,Salário,3200.0,App,Ana,SP,Premium
1,2,Débito,Alimentação,150.0,Agência,Bruno,RJ,Básico
2,1,Débito,Transporte,1500.0,App,Ana,SP,Premium
3,3,Crédito,Salário,4500.0,Internet Banking,Carlos,MG,Intermediário
4,2,Crédito,Lazer,200.0,App,Bruno,RJ,Básico
5,1,Débito,Alimentação,80.0,Agência,Ana,SP,Premium
6,3,Débito,Transporte,1500.0,App,Carlos,MG,Intermediário
7,2,Crédito,Salário,2800.0,Internet Banking,Bruno,RJ,Básico

#### *Banco Fácil -- Programa de Dados*