# 🏦💼 DESAFIO FINAL — ANÁLISE DE CORRENTISTAS

Você é analista de dados de um banco e recebeu duas bases:

- 📊 Clientes (`df_clientes`)
- 💳 Transações (`df_transacoes`)

Seu objetivo é limpar, tratar e gerar insights estratégicos.

## 📦 1. Criação dos DataFrames

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)

# Clientes
df_clientes = pd.DataFrame({
    'id_cliente': np.arange(1, 101),
    'nome': ['Cliente_' + str(i) for i in range(1, 101)],
    'idade': np.random.choice([25, 30, 35, 40, np.nan], 100),
    'cidade': np.random.choice(['RJ', 'SP', 'MG', None], 100),
    'status_conta': np.random.choice(['Ativa', 'Inativa', None], 100),
    'score_credito': np.random.choice([300, 500, 700, 900, np.nan], 100),
    'renda_mensal': np.random.choice([2000, 4000, 6000, 8000, np.nan], 100),
    'segmento': np.random.choice(['Varejo', 'Alta Renda', None], 100)
})

# Inserindo duplicados
df_clientes = pd.concat([df_clientes, df_clientes.iloc[:5]])

# Transações
df_transacoes = pd.DataFrame({
    'id_cliente': np.random.randint(1, 101, 200),
    'valor_transacao': np.random.choice([100, 500, 1000, 2000, np.nan], 200),
    'tipo': np.random.choice(['Crédito', 'Débito'], 200),
    'mes': np.random.choice(['Jan', 'Fev', 'Mar'], 200)
})

df_clientes.head()

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento
0,1,Cliente_1,40.0,None,None,700.0,8000.0,Varejo
1,2,Cliente_2,NaN,MG,Ativa,300.0,4000.0,None
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.0,Alta Renda
3,4,Cliente_4,NaN,None,Ativa,300.0,8000.0,Alta Renda
4,5,Cliente_5,NaN,None,Ativa,NaN,NaN,Varejo

In [24]:
print(df_clientes.info())

<class 'pandas.core.frame.DataFrame'>
Index: 105 entries, 0 to 4
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_cliente     105 non-null    int64
 1   nome           105 non-null    object
 2   idade          83 non-null     float64
 3   cidade         78 non-null     object
 4   status_conta   68 non-null     object
 5   score_credito  86 non-null     float64
 6   renda_mensal   79 non-null     float64
 7   segmento       72 non-null     object
dtypes: float64(3), int64(1), object(4)
memory usage: 7.4+ KB
None

In [25]:
print(df_transacoes.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_cliente       200 non-null    int32
 1   valor_transacao  165 non-null    float64
 2   tipo             200 non-null    object
 3   mes              200 non-null    object
dtypes: float64(1), int32(1), object(2)
memory usage: 5.6+ KB
None

## 🎯 MISSÃO DO ALUNO

### 🔎 PARTE 1 — Diagnóstico

**Pergunta 1**  
Quantos valores nulos existem por coluna?

**Pergunta 2**  
Existem registros duplicados?

In [11]:
#Valores nulos tabela clientes
print(df_clientes.isna().sum())
print('='*30)
#Valores nulos tabela transações
print(df_transacoes.isna().sum())

id_cliente        0
nome              0
idade            22
cidade           27
status_conta     37
score_credito    19
renda_mensal     26
segmento         33
dtype: int64
==============================
id_cliente          0
valor_transacao    35
tipo                0
mes                 0
dtype: int64

In [9]:
#Valores Duplicados

print('Quantidade de registros duplicados da tabela clientes: ', df_clientes.duplicated().sum())
print('='*30)
print('Quantidade de registros duplicados da tabela transações: ', df_transacoes.duplicated().sum())

Quantidade de registros duplicados da tabela clientes:  5
==============================
Quantidade de registros duplicados da tabela transações:  6

### 📊 PARTE 2 — Análise exploratória

**Pergunta 3**  
Quantas cidades diferentes existem?

**Pergunta 4**  
Distribuição de status da conta

In [21]:
#Quantidade de cidades diferentes
print(df_clientes['cidade'].unique())
print(df_clientes['cidade'].nunique())

[None 'MG' 'RJ' 'SP']
3

In [28]:
#Distribuição do Status Conta
print((df_clientes['status_conta'].value_counts(normalize=True)*100).round(2))

status_conta
Ativa      54.41
Inativa    45.59
Name: proportion, dtype: float64

### 🧹 PARTE 3 — Limpeza de dados

**Pergunta 5**  
Remova duplicados  

**Pergunta 6**  
Preencha valores faltantes:
- idade → mediana  
- renda → média  
- cidade → "Não Informado"  
- status → ffill

In [23]:
#Removendo duplicados

df_clientes_novo = df_clientes.drop_duplicates(keep='first')
display(df_clientes_novo)

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento
0,1,Cliente_1,40.0,None,None,700.0,8000.0,Varejo
1,2,Cliente_2,NaN,MG,Ativa,300.0,4000.0,None
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.0,Alta Renda
3,4,Cliente_4,NaN,None,Ativa,300.0,8000.0,Alta Renda
4,5,Cliente_5,NaN,None,Ativa,NaN,NaN,Varejo
...,...,...,...,...,...,...,...,...
95,96,Cliente_96,35.0,RJ,Ativa,500.0,2000.0,Varejo
96,97,Cliente_97,NaN,MG,None,NaN,4000.0,Alta Renda
97,98,Cliente_98,30.0,MG,Ativa,500.0,6000.0,Alta Renda
98,99,Cliente_99,30.0,SP,Inativa,500.0,8000.0,Varejo
99,100,Cliente_100,25.0,None,Inativa,300.0,NaN,Varejo

In [ ]:
df_clientes_novo['cidade'] = df_clientes_novo.loc['cidade'].fillna('Não Informado')
display(df_clientes_novo)

C:\Users\dikel\AppData\Local\Temp\ipykernel_18168\3421270377.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clientes_novo['cidade'] = df_clientes_novo['cidade'].fillna('Não Informado')

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento
0,1,Cliente_1,40.0,Não Informado,None,700.0,8000.0,Varejo
1,2,Cliente_2,NaN,MG,Ativa,300.0,4000.0,None
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.0,Alta Renda
3,4,Cliente_4,NaN,Não Informado,Ativa,300.0,8000.0,Alta Renda
4,5,Cliente_5,NaN,Não Informado,Ativa,NaN,NaN,Varejo
...,...,...,...,...,...,...,...,...
95,96,Cliente_96,35.0,RJ,Ativa,500.0,2000.0,Varejo
96,97,Cliente_97,NaN,MG,None,NaN,4000.0,Alta Renda
97,98,Cliente_98,30.0,MG,Ativa,500.0,6000.0,Alta Renda
98,99,Cliente_99,30.0,SP,Inativa,500.0,8000.0,Varejo
99,100,Cliente_100,25.0,Não Informado,Inativa,300.0,NaN,Varejo

In [33]:
df_clientes_novo['renda_mensal'] = df_clientes_novo['renda_mensal'].fillna((df_clientes_novo['renda_mensal'].mean()).round(2))
display(df_clientes_novo)

C:\Users\dikel\AppData\Local\Temp\ipykernel_18168\2893387904.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clientes_novo['renda_mensal'] = df_clientes_novo['renda_mensal'].fillna((df_clientes_novo['renda_mensal'].mean()).round(2))

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento
0,1,Cliente_1,40.0,Não Informado,None,700.0,8000.000000,Varejo
1,2,Cliente_2,NaN,MG,Ativa,300.0,4000.000000,None
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.000000,Alta Renda
3,4,Cliente_4,NaN,Não Informado,Ativa,300.0,8000.000000,Alta Renda
4,5,Cliente_5,NaN,Não Informado,Ativa,NaN,5253.333333,Varejo
...,...,...,...,...,...,...,...,...
95,96,Cliente_96,35.0,RJ,Ativa,500.0,2000.000000,Varejo
96,97,Cliente_97,NaN,MG,None,NaN,4000.000000,Alta Renda
97,98,Cliente_98,30.0,MG,Ativa,500.0,6000.000000,Alta Renda
98,99,Cliente_99,30.0,SP,Inativa,500.0,8000.000000,Varejo
99,100,Cliente_100,25.0,Não Informado,Inativa,300.0,5253.333333,Varejo

In [34]:
df_clientes_novo['idade'] = df_clientes_novo['idade'].fillna(df_clientes_novo['idade'].median())
display(df_clientes_novo)

C:\Users\dikel\AppData\Local\Temp\ipykernel_18168\1104078348.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clientes_novo['idade'] = df_clientes_novo['idade'].fillna(df_clientes_novo['idade'].median())

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento
0,1,Cliente_1,40.0,Não Informado,None,700.0,8000.000000,Varejo
1,2,Cliente_2,35.0,MG,Ativa,300.0,4000.000000,None
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.000000,Alta Renda
3,4,Cliente_4,35.0,Não Informado,Ativa,300.0,8000.000000,Alta Renda
4,5,Cliente_5,35.0,Não Informado,Ativa,NaN,5253.333333,Varejo
...,...,...,...,...,...,...,...,...
95,96,Cliente_96,35.0,RJ,Ativa,500.0,2000.000000,Varejo
96,97,Cliente_97,35.0,MG,None,NaN,4000.000000,Alta Renda
97,98,Cliente_98,30.0,MG,Ativa,500.0,6000.000000,Alta Renda
98,99,Cliente_99,30.0,SP,Inativa,500.0,8000.000000,Varejo
99,100,Cliente_100,25.0,Não Informado,Inativa,300.0,5253.333333,Varejo

In [38]:
df_clientes_novo['status_conta'] = df_clientes_novo['status_conta'].bfill()
display(df_clientes_novo)

C:\Users\dikel\AppData\Local\Temp\ipykernel_18168\3852316537.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clientes_novo['status_conta'] = df_clientes_novo['status_conta'].bfill()

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento
0,1,Cliente_1,40.0,Não Informado,Ativa,700.0,8000.000000,Varejo
1,2,Cliente_2,35.0,MG,Ativa,300.0,4000.000000,None
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.000000,Alta Renda
3,4,Cliente_4,35.0,Não Informado,Ativa,300.0,8000.000000,Alta Renda
4,5,Cliente_5,35.0,Não Informado,Ativa,NaN,5253.333333,Varejo
...,...,...,...,...,...,...,...,...
95,96,Cliente_96,35.0,RJ,Ativa,500.0,2000.000000,Varejo
96,97,Cliente_97,35.0,MG,Ativa,NaN,4000.000000,Alta Renda
97,98,Cliente_98,30.0,MG,Ativa,500.0,6000.000000,Alta Renda
98,99,Cliente_99,30.0,SP,Inativa,500.0,8000.000000,Varejo
99,100,Cliente_100,25.0,Não Informado,Inativa,300.0,5253.333333,Varejo

In [39]:
print(df_clientes_novo.isna().sum())

id_cliente        0
nome              0
idade             0
cidade            0
status_conta      0
score_credito    18
renda_mensal      0
segmento         32
dtype: int64

### 🔁 PARTE 4 — Regras de negócio

**Pergunta 7**  
Crie a coluna `perfil_risco`:
- "Alto Risco" → score < 500  
- "Médio" → 500–700  
- "Baixo Risco" → > 700

In [58]:
df_clientes_novo['perfil_risco'] = np.where(
    df_clientes_novo['score_credito'] > 700, 
    'Baixo Risco', 
    np.where(df_clientes_novo['score_credito'] > 500,
             'Médio Risco', 
             'Alto Risco'
             )
)
display(df_clientes_novo)

C:\Users\dikel\AppData\Local\Temp\ipykernel_18168\642107997.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_clientes_novo['perfil_risco'] = np.where(

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento,perfil_risco
0,1,Cliente_1,40.0,Não Informado,Ativa,700.0,8000.000000,Varejo,Médio Risco
1,2,Cliente_2,35.0,MG,Ativa,300.0,4000.000000,None,Alto Risco
2,3,Cliente_3,35.0,RJ,Inativa,700.0,6000.000000,Alta Renda,Médio Risco
3,4,Cliente_4,35.0,Não Informado,Ativa,300.0,8000.000000,Alta Renda,Alto Risco
4,5,Cliente_5,35.0,Não Informado,Ativa,NaN,5253.333333,Varejo,Alto Risco
...,...,...,...,...,...,...,...,...,...
95,96,Cliente_96,35.0,RJ,Ativa,500.0,2000.000000,Varejo,Alto Risco
96,97,Cliente_97,35.0,MG,Ativa,NaN,4000.000000,Alta Renda,Alto Risco
97,98,Cliente_98,30.0,MG,Ativa,500.0,6000.000000,Alta Renda,Alto Risco
98,99,Cliente_99,30.0,SP,Inativa,500.0,8000.000000,Varejo,Alto Risco
99,100,Cliente_100,25.0,Não Informado,Inativa,300.0,5253.333333,Varejo,Alto Risco

In [45]:
df_clientes_novo['perfil_risco'].value_counts(normalize=True)*100

perfil_risco
Alto Risco     63.0
Médio Risco    20.0
Baixo Risco    17.0
Name: proportion, dtype: float64

### 🔗 PARTE 5 — JOIN

**Pergunta 8**  
Faça um inner join entre clientes e transações, considere o dataframe sem duplicidade

**Pergunta 9**  
Faça um left join, considere o dataframe sem duplicidade

In [46]:
df_unificado = pd.merge(
    df_transacoes,
    df_clientes_novo,
    on='id_cliente',
    how='inner'
)
display(df_unificado)

,id_cliente,valor_transacao,tipo,mes,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento,perfil_risco
0,7,2000.0,Débito,Mar,Cliente_7,35.0,RJ,Inativa,500.0,5253.333333,Alta Renda,Alto Risco
1,46,500.0,Crédito,Fev,Cliente_46,25.0,Não Informado,Ativa,900.0,8000.000000,None,Baixo Risco
2,13,500.0,Débito,Fev,Cliente_13,35.0,RJ,Inativa,300.0,5253.333333,Alta Renda,Alto Risco
3,40,500.0,Crédito,Mar,Cliente_40,30.0,RJ,Inativa,300.0,5253.333333,None,Alto Risco
4,42,500.0,Crédito,Fev,Cliente_42,25.0,MG,Inativa,900.0,5253.333333,Varejo,Baixo Risco
...,...,...,...,...,...,...,...,...,...,...,...,...
195,85,2000.0,Crédito,Jan,Cliente_85,25.0,RJ,Inativa,900.0,6000.000000,Alta Renda,Baixo Risco
196,14,1000.0,Crédito,Jan,Cliente_14,30.0,MG,Ativa,900.0,8000.000000,Alta Renda,Baixo Risco
197,66,1000.0,Débito,Jan,Cliente_66,40.0,SP,Ativa,500.0,5253.333333,None,Alto Risco
198,75,100.0,Crédito,Mar,Cliente_75,35.0,Não Informado,Inativa,NaN,5253.333333,Varejo,Alto Risco
199,51,2000.0,Débito,Fev,Cliente_51,40.0,RJ,Inativa,NaN,5253.333333,Varejo,Alto Risco

In [47]:
df_unificado_left = pd.merge(
    df_clientes_novo,
    df_transacoes,
    on='id_cliente',
    how='left'
)
display(df_unificado_left)

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento,perfil_risco,valor_transacao,tipo,mes
0,1,Cliente_1,40.0,Não Informado,Ativa,700.0,8000.000000,Varejo,Médio Risco,500.0,Débito,Mar
1,1,Cliente_1,40.0,Não Informado,Ativa,700.0,8000.000000,Varejo,Médio Risco,2000.0,Crédito,Jan
2,1,Cliente_1,40.0,Não Informado,Ativa,700.0,8000.000000,Varejo,Médio Risco,100.0,Débito,Fev
3,1,Cliente_1,40.0,Não Informado,Ativa,700.0,8000.000000,Varejo,Médio Risco,NaN,Crédito,Jan
4,2,Cliente_2,35.0,MG,Ativa,300.0,4000.000000,None,Alto Risco,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
204,97,Cliente_97,35.0,MG,Ativa,NaN,4000.000000,Alta Renda,Alto Risco,NaN,NaN,NaN
205,98,Cliente_98,30.0,MG,Ativa,500.0,6000.000000,Alta Renda,Alto Risco,100.0,Débito,Jan
206,99,Cliente_99,30.0,SP,Inativa,500.0,8000.000000,Varejo,Alto Risco,100.0,Crédito,Jan
207,99,Cliente_99,30.0,SP,Inativa,500.0,8000.000000,Varejo,Alto Risco,1000.0,Débito,Fev
208,100,Cliente_100,25.0,Não Informado,Inativa,300.0,5253.333333,Varejo,Alto Risco,NaN,Débito,Mar

### 📊 PARTE 6 — Análise estratégica

**Pergunta 10**  
Qual o valor total transacionado por perfil de risco?

**Pergunta 11**  
Qual a média de transação por segmento?  

**Pergunta 12**  
Qual cidade tem maior volume financeiro?  

**Pergunta 13**  
Quantos clientes de alto risco possuem renda alta (> 6000)?  

**Pergunta 14**  
Qual o ticket médio por tipo de transação?  

**Pergunta 15**  
Liste clientes sem transações (apenas no left join)

In [50]:
df_unificado.groupby('perfil_risco')['valor_transacao'].sum()

perfil_risco
Alto Risco     81200.0
Baixo Risco    21200.0
Médio Risco    41700.0
Name: valor_transacao, dtype: float64

In [51]:
df_unificado.groupby('segmento')['valor_transacao'].mean()

segmento
Alta Renda    902.380952
Varejo        862.857143
Name: valor_transacao, dtype: float64

In [53]:
df_unificado.groupby('cidade')['valor_transacao'].sum()

cidade
MG               32200.0
Não Informado    37700.0
RJ               43000.0
SP               31200.0
Name: valor_transacao, dtype: float64

In [77]:
df_unificado.groupby('tipo')['valor_transacao'].mean().round(2)

tipo
Crédito    795.51
Débito     964.47
Name: valor_transacao, dtype: float64

In [71]:
filtro = df_unificado[(df_unificado['perfil_risco'] == 'Alto Risco') & (df_unificado['renda_mensal'] > 6000)]
display(filtro)

,id_cliente,valor_transacao,tipo,mes,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento,perfil_risco
13,83,1000.0,Crédito,Fev,Cliente_83,35.0,MG,Inativa,500.0,8000.0,Alta Renda,Alto Risco
14,8,100.0,Crédito,Jan,Cliente_8,35.0,Não Informado,Inativa,500.0,8000.0,None,Alto Risco
16,86,NaN,Débito,Fev,Cliente_86,25.0,MG,Ativa,NaN,8000.0,None,Alto Risco
21,4,100.0,Débito,Mar,Cliente_4,35.0,Não Informado,Ativa,300.0,8000.0,Alta Renda,Alto Risco
25,19,500.0,Débito,Fev,Cliente_19,25.0,MG,Inativa,300.0,8000.0,Varejo,Alto Risco
26,61,NaN,Crédito,Jan,Cliente_61,30.0,MG,Inativa,300.0,8000.0,Varejo,Alto Risco
32,19,1000.0,Débito,Fev,Cliente_19,25.0,MG,Inativa,300.0,8000.0,Varejo,Alto Risco
42,61,500.0,Crédito,Mar,Cliente_61,30.0,MG,Inativa,300.0,8000.0,Varejo,Alto Risco
46,77,1000.0,Débito,Fev,Cliente_77,25.0,Não Informado,Inativa,500.0,8000.0,None,Alto Risco
60,61,100.0,Crédito,Fev,Cliente_61,30.0,MG,Inativa,300.0,8000.0,Varejo,Alto Risco
63,80,1000.0,Crédito,Fev,Cliente_80,40.0,MG,Inativa,300.0,8000.0,Varejo,Alto Risco
67,99,100.0,Crédito,Jan,Cliente_99,30.0,SP,Inativa,500.0,8000.0,Varejo,Alto Risco
68,19,1000.0,Débito,Jan,Cliente_19,25.0,MG,Inativa,300.0,8000.0,Varejo,Alto Risco
70,57,100.0,Débito,Mar,Cliente_57,40.0,RJ,Ativa,NaN,8000.0,None,Alto Risco
80,16,500.0,Débito,Fev,Cliente_16,30.0,Não Informado,Inativa,NaN,8000.0,Alta Renda,Alto Risco
82,57,500.0,Débito,Jan,Cliente_57,40.0,RJ,Ativa,NaN,8000.0,None,Alto Risco
87,16,2000.0,Débito,Mar,Cliente_16,30.0,Não Informado,Inativa,NaN,8000.0,Alta Renda,Alto Risco
90,24,500.0,Crédito,Jan,Cliente_24,25.0,SP,Ativa,NaN,8000.0,Varejo,Alto Risco
92,8,1000.0,Débito,Jan,Cliente_8,35.0,Não Informado,Inativa,500.0,8000.0,None,Alto Risco
96,8,500.0,Débito,Mar,Cliente_8,35.0,Não Informado,Inativa,500.0,8000.0,None,Alto Risco
111,77,500.0,Débito,Mar,Cliente_77,25.0,Não Informado,Inativa,500.0,8000.0,None,Alto Risco
119,69,NaN,Débito,Mar,Cliente_69,40.0,SP,Ativa,500.0,8000.0,None,Alto Risco
123,10,1000.0,Débito,Jan,Cliente_10,35.0,MG,Inativa,NaN,8000.0,Varejo,Alto Risco
137,86,2000.0,Crédito,Jan,Cliente_86,25.0,MG,Ativa,NaN,8000.0,None,Alto Risco
141,77,1000.0,Crédito,Fev,Cliente_77,25.0,Não Informado,Inativa,500.0,8000.0,None,Alto Risco
144,99,1000.0,Débito,Fev,Cliente_99,30.0,SP,Inativa,500.0,8000.0,Varejo,Alto Risco
151,69,2000.0,Crédito,Mar,Cliente_69,40.0,SP,Ativa,500.0,8000.0,None,Alto Risco
161,83,100.0,Débito,Fev,Cliente_83,35.0,MG,Inativa,500.0,8000.0,Alta Renda,Alto Risco
169,77,100.0,Crédito,Mar,Cliente_77,25.0,Não Informado,Inativa,500.0,8000.0,None,Alto Risco
170,4,500.0,Crédito,Jan,Cliente_4,35.0,Não Informado,Ativa,300.0,8000.0,Alta Renda,Alto Risco
190,57,500.0,Débito,Jan,Cliente_57,40.0,RJ,Ativa,NaN,8000.0,None,Alto Risco

In [74]:
display(df_unificado_left.loc[df_unificado_left['valor_transacao'].isna()])

,id_cliente,nome,idade,cidade,status_conta,score_credito,renda_mensal,segmento,perfil_risco,valor_transacao,tipo,mes
3,1,Cliente_1,40.0,Não Informado,Ativa,700.0,8000.000000,Varejo,Médio Risco,NaN,Crédito,Jan
4,2,Cliente_2,35.0,MG,Ativa,300.0,4000.000000,None,Alto Risco,NaN,NaN,NaN
12,5,Cliente_5,35.0,Não Informado,Ativa,NaN,5253.333333,Varejo,Alto Risco,NaN,Crédito,Mar
14,5,Cliente_5,35.0,Não Informado,Ativa,NaN,5253.333333,Varejo,Alto Risco,NaN,Crédito,Fev
38,17,Cliente_17,40.0,SP,Inativa,900.0,5253.333333,Alta Renda,Baixo Risco,NaN,Crédito,Mar
40,18,Cliente_18,35.0,MG,Inativa,700.0,4000.000000,None,Médio Risco,NaN,Crédito,Fev
45,20,Cliente_20,40.0,RJ,Ativa,300.0,4000.000000,None,Alto Risco,NaN,Crédito,Mar
46,21,Cliente_21,30.0,MG,Ativa,900.0,6000.000000,Alta Renda,Baixo Risco,NaN,Crédito,Fev
48,22,Cliente_22,35.0,RJ,Ativa,700.0,2000.000000,Varejo,Médio Risco,NaN,NaN,NaN
63,30,Cliente_30,40.0,MG,Ativa,300.0,2000.000000,Varejo,Alto Risco,NaN,Crédito,Jan
64,31,Cliente_31,35.0,SP,Ativa,900.0,8000.000000,Alta Renda,Baixo Risco,NaN,Débito,Fev
65,31,Cliente_31,35.0,SP,Ativa,900.0,8000.000000,Alta Renda,Baixo Risco,NaN,Crédito,Fev
68,33,Cliente_33,40.0,MG,Ativa,NaN,2000.000000,Varejo,Alto Risco,NaN,Débito,Mar
73,34,Cliente_34,25.0,RJ,Inativa,900.0,4000.000000,None,Baixo Risco,NaN,Crédito,Jan
77,36,Cliente_36,35.0,MG,Ativa,700.0,2000.000000,None,Médio Risco,NaN,Débito,Jan
81,38,Cliente_38,35.0,SP,Inativa,700.0,2000.000000,Varejo,Médio Risco,NaN,Crédito,Fev
82,39,Cliente_39,25.0,Não Informado,Inativa,300.0,5253.333333,None,Alto Risco,NaN,Débito,Mar
84,39,Cliente_39,25.0,Não Informado,Inativa,300.0,5253.333333,None,Alto Risco,NaN,Débito,Mar
89,43,Cliente_43,40.0,Não Informado,Ativa,NaN,5253.333333,Varejo,Alto Risco,NaN,NaN,NaN
102,48,Cliente_48,35.0,Não Informado,Inativa,NaN,6000.000000,None,Alto Risco,NaN,NaN,NaN
111,52,Cliente_52,40.0,MG,Ativa,700.0,8000.000000,Varejo,Médio Risco,NaN,NaN,NaN
125,58,Cliente_58,30.0,Não Informado,Ativa,300.0,4000.000000,None,Alto Risco,NaN,Crédito,Fev
129,61,Cliente_61,30.0,MG,Inativa,300.0,8000.000000,Varejo,Alto Risco,NaN,Crédito,Jan
132,62,Cliente_62,40.0,MG,Inativa,500.0,2000.000000,None,Alto Risco,NaN,Crédito,Jan
138,65,Cliente_65,30.0,Não Informado,Ativa,500.0,4000.000000,Alta Renda,Alto Risco,NaN,Débito,Mar
140,65,Cliente_65,30.0,Não Informado,Ativa,500.0,4000.000000,Alta Renda,Alto Risco,NaN,Débito,Fev
146,68,Cliente_68,30.0,RJ,Inativa,500.0,4000.000000,Alta Renda,Alto Risco,NaN,NaN,NaN
147,69,Cliente_69,40.0,SP,Ativa,500.0,8000.000000,None,Alto Risco,NaN,Débito,Mar
151,72,Cliente_72,35.0,SP,Ativa,300.0,6000.000000,None,Alto Risco,NaN,Crédito,Mar
152,72,Cliente_72,35.0,SP,Ativa,300.0,6000.000000,None,Alto Risco,NaN,Débito,Mar
171,81,Cliente_81,35.0,Não Informado,Ativa,NaN,6000.000000,Varejo,Alto Risco,NaN,Débito,Fev
175,84,Cliente_84,35.0,Não Informado,Ativa,300.0,4000.000000,None,Alto Risco,NaN,Crédito,Fev
178,85,Cliente_85,25.0,RJ,Inativa,900.0,6000.000000,Alta Renda,Baixo Risco,NaN,Crédito,Fev
180,86,Cliente_86,25.0,MG,Ativa,NaN,8000.000000,None,Alto Risco,NaN,Débito,Fev
182,87,Cliente_87,25.0,SP,Ativa,900.0,2000.000000,Alta Renda,Baixo Risco,NaN,Débito,Mar
183,88,Cliente_88,25.0,RJ,Ativa,300.0,2000.000000,Varejo,Alto Risco,NaN,NaN,NaN
185,89,Cliente_89,40.0,RJ,Ativa,900.0,5253.333333,None,Baixo Risco,NaN,Crédito,Fev
191,92,Cliente_92,25.0,SP,Ativa,500.0,5253.333333,None,Alto Risco,NaN,Débito,Jan
197,93,Cliente_93,35.0,RJ,Ativa,500.0,8000.000000,None,Alto Risco,NaN,NaN,NaN
200,95,Cliente_95,25.0,RJ,Inativa,300.0,2000.000000,None,Alto Risco,NaN,Débito,Jan
201,95,Cliente_95,25.0,RJ,Inativa,300.0,2000.000000,None,Alto Risco,NaN,Crédito,Jan
203,96,Cliente_96,35.0,RJ,Ativa,500.0,2000.000000,Varejo,Alto Risco,NaN,Débito,Mar
204,97,Cliente_97,35.0,MG,Ativa,NaN,4000.000000,Alta Renda,Alto Risco,NaN,NaN,NaN
208,100,Cliente_100,25.0,Não Informado,Inativa,300.0,5253.333333,Varejo,Alto Risco,NaN,Débito,Mar

### ✏️ PARTE 7 — Ajustes pontuais

**Pergunta 16**  
Altere a cidade do primeiro cliente para "ES"

**Pergunta 17**  
Acesse o valor da renda do cliente na linha 10

### 🧠📊 Questão — Integração e Análise de Clientes

Você possui dois DataFrames:

- df_clientes → informações dos correntistas
- df_transacoes → movimentações financeiras

Faça um left join entre df_clientes e df_transacoes utilizando a coluna id_cliente.

Em seguida:

👉 Calcule o valor total transacionado por cliente

👉 Mostre o resultado ordenado do maior para o menor

👉 Importante: clientes sem transações devem aparecer com valor 0

### 🧠📉 Nova questão (focada em saldo negativo)

Após realizar o left join entre clientes e transações:

👉 Considere que:

- valores de transação do tipo "Débito" devem ser negativos
- valores de "Crédito" permanecem positivos

👉 Calcule o saldo final por cliente (soma das transações)

👉 Em seguida:

1. Liste os clientes com saldo negativo
2. Mostre quantos clientes estão nessa situação
3. Calcule o saldo médio desses clientes