## ✏️ Exercícios de Fixação

In [3]:
import pandas as pd
import numpy as np

**EXERCICIO 1**

**Enunciado:**
Você recebeu um arquivo CSV `alunos.csv` com dados de alunos. Sem abrir em Excel, use Python para:
1. Quantas linhas e colunas o arquivo tem?
2. Quais são os tipos de dados de cada coluna?
3. Qual coluna tem mais valores faltantes?
4. Quantas linhas duplicadas existem?

**Dica:** Use `shape`, `info()`, `isna().sum()`, `duplicated().sum()`

In [4]:
alunos = pd.read_csv('C:/Temp/alunos.csv', encoding='UTF-8')
display(alunos)

    id      nome  idade  nota              email
0    1       Ana   20.0   8.5      ana@email.com
1    2     Bruno   22.0   7.0    bruno@email.com
2    3    Carlos    NaN   6.5                NaN
3    4   Daniela   21.0   9.0  daniela@email.com
4    5   Eduardo   23.0   NaN  eduardo@email.com
5    6  Fernanda   20.0   8.0                NaN
6    7   Gabriel   22.0   7.5  gabriel@email.com
7    8    Helena   21.0   8.2   helena@email.com
8    9      Igor    NaN   6.8                NaN
9   10     Julia   20.0   9.1    julia@email.com
10  10     Julia   20.0   9.1    julia@email.com

**1. Resposta**

In [5]:
display(alunos.shape)

(11, 5)

**2. Resposta**

In [6]:
display(alunos.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      11 non-null     int64
 1   nome    11 non-null     object
 2   idade   9 non-null      float64
 3   nota    10 non-null     float64
 4   email   8 non-null      object
dtypes: float64(2), int64(1), object(2)
memory usage: 572.0+ bytes

None

**3. Resposta**

In [7]:
display('Valores Faltantes por coluna: \n', alunos.isna().sum())

'Valores Faltantes por coluna: \n'

id       0
nome     0
idade    2
nota     1
email    3
dtype: int64

In [8]:
display(alunos.duplicated().sum())
display(alunos.duplicated())

np.int64(1)

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

**EXERCICIO 2**

**Enunciado:**
O DataFrame `vendas` tem 10 linhas. Coluna 'email' tem 2 valores faltantes (5%), coluna 'telefone' tem 4 faltantes (40%), coluna 'valor' tem 2 faltantes (5%).

Para qual coluna você usa `dropna()` e para qual você usa `fillna()`? Por quê?

```python
# Seu código aqui:
# df = pd.read_csv('vendas.csv')
# ... completar
```

**Dica:** Pense em qual percentual é "aceitável" remover. 5% é OK, 40% é demais.

In [16]:
vendas = pd.read_csv('C:/Temp/vendas.csv', sep=';', encoding='UTF-8')

In [23]:
vendas.head(20)

   id                email      telefone  valor  valor_compra estado
0   1   cliente1@email.com  2.199999e+10  100.0           100     SP
1   2   cliente2@email.com           NaN  200.0           200     RJ
2   3                  NaN  2.199999e+10  150.0           150     MG
3   4   cliente4@email.com           NaN    NaN           300     SP
4   5   cliente5@email.com  2.199999e+10  250.0           250     RJ
5   6   cliente6@email.com           NaN  180.0           180     MG
6   7   cliente7@email.com           NaN    NaN           220     ES
7   8   cliente8@email.com  2.199999e+10  130.0           130     SP
8   9                  NaN  2.199999e+10  170.0           170     RJ
9  10  cliente10@email.com           NaN  190.0           190     MG

In [20]:
print(vendas.shape)
print(vendas.info())

(10, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            10 non-null     int64
 1   email         8 non-null      object
 2   telefone      5 non-null      float64
 3   valor         8 non-null      float64
 4   valor_compra  10 non-null     int64
 5   estado        10 non-null     object
dtypes: float64(2), int64(2), object(2)
memory usage: 612.0+ bytes
None

In [31]:
vendas['email'] = vendas['email'].fillna('email não cadastrado')
display(vendas)

   id                 email      telefone  valor  valor_compra estado  imposto
0   1    cliente1@email.com  2.199999e+10  100.0           100     SP     0.18
1   2    cliente2@email.com           NaN  200.0           200     RJ     0.20
2   3  email não cadastrado  2.199999e+10  150.0           150     MG     0.15
3   4    cliente4@email.com           NaN    NaN           300     SP     0.18
4   5    cliente5@email.com  2.199999e+10  250.0           250     RJ     0.20
5   6    cliente6@email.com           NaN  180.0           180     MG     0.15
6   7    cliente7@email.com           NaN    NaN           220     ES     0.17
7   8    cliente8@email.com  2.199999e+10  130.0           130     SP     0.18
8   9  email não cadastrado  2.199999e+10  170.0           170     RJ     0.20
9  10   cliente10@email.com           NaN  190.0           190     MG     0.15

In [32]:
vendas['telefone'] = vendas['telefone'].fillna('telefone não cadastrado')
display(vendas)

,id,email,telefone,valor,valor_compra,estado,imposto
0,1,cliente1@email.com,21999990001.0,100.0,100,SP,0.18
1,2,cliente2@email.com,telefone não cadastrado,200.0,200,RJ,0.20
2,3,email não cadastrado,21999990003.0,150.0,150,MG,0.15
3,4,cliente4@email.com,telefone não cadastrado,NaN,300,SP,0.18
4,5,cliente5@email.com,21999990005.0,250.0,250,RJ,0.20
5,6,cliente6@email.com,telefone não cadastrado,180.0,180,MG,0.15
6,7,cliente7@email.com,telefone não cadastrado,NaN,220,ES,0.17
7,8,cliente8@email.com,21999990008.0,130.0,130,SP,0.18
8,9,email não cadastrado,21999990009.0,170.0,170,RJ,0.20
9,10,cliente10@email.com,telefone não cadastrado,190.0,190,MG,0.15

In [33]:
vendas['valor'] = vendas['valor'].fillna(vendas['valor_compra'])
display(vendas)

,id,email,telefone,valor,valor_compra,estado,imposto
0,1,cliente1@email.com,21999990001.0,100.0,100,SP,0.18
1,2,cliente2@email.com,telefone não cadastrado,200.0,200,RJ,0.20
2,3,email não cadastrado,21999990003.0,150.0,150,MG,0.15
3,4,cliente4@email.com,telefone não cadastrado,300.0,300,SP,0.18
4,5,cliente5@email.com,21999990005.0,250.0,250,RJ,0.20
5,6,cliente6@email.com,telefone não cadastrado,180.0,180,MG,0.15
6,7,cliente7@email.com,telefone não cadastrado,220.0,220,ES,0.17
7,8,cliente8@email.com,21999990008.0,130.0,130,SP,0.18
8,9,email não cadastrado,21999990009.0,170.0,170,RJ,0.20
9,10,cliente10@email.com,telefone não cadastrado,190.0,190,MG,0.15

**Resposta:** Usaria `fillna()`para coluna valores usando o mesmo valor da coluna `valor_compra` e para coluna `email` com a mensagem `email não informado`

**EXERCICIO 3**

**Enunciado:**
Você recebeu `produtos.csv`:

```
id,nome,preco,estoque,categoria,data_cadastro
1,Notebook,R$ 2500,150,Eletrônicos,2024-01-15
1,Notebook,R$ 2500,150,Eletrônicos,2024-01-15
2,Mouse,500,?,Periféricos,2024-01-16
3,Teclado,150.50,80,,2024-01-17
4,Monitor,,50,Eletrônicos,
```

Limpe esse dataset:
1. Remova duplicatas
2. Converta 'preco' de texto para número
3. Trate valores faltantes em 'estoque' (preencha com 0)
4. Trate valores faltantes em 'categoria' (preencha com 'Sem categoria')
5. Mostre as linhas onde 'data_cadastro' é vazia
6. Mostre quantas linhas sobraram

**Dica:** Use `drop_duplicates()`, `str.replace()`, `pd.to_numeric()`, `fillna()`

In [ ]:
# Importando CSV
produtos = pd.read_csv('produtos.csv', encoding='UTF-8')
display(produtos.head(10))

   id      nome    preco estoque    categoria data_cadastro
0   1  Notebook  R$ 2500     150  Eletrônicos    2024-01-15
1   1  Notebook  R$ 2500     150  Eletrônicos    2024-01-15
2   2     Mouse      500       ?  Periféricos    2024-01-16
3   3   Teclado   150.50      80          NaN    2024-01-17
4   4   Monitor      NaN      50  Eletrônicos           NaN

In [ ]:
# Removendo duplicadas
produtos = produtos.drop_duplicates(keep='first')
display(produtos)

   id      nome    preco estoque    categoria data_cadastro
0   1  Notebook  R$ 2500     150  Eletrônicos    2024-01-15
2   2     Mouse      500       ?  Periféricos    2024-01-16
3   3   Teclado   150.50      80          NaN    2024-01-17
4   4   Monitor      NaN      50  Eletrônicos           NaN

In [ ]:
produtos[]

**EXERCICIO 4**

**Enunciado:**
Você tem `vendas.csv` com coluna 'valor_compra' (em números) e 'estado' (ex: SP, RJ, MG).

Crie uma nova coluna 'imposto':
- Se estado == 'SP': 18% de imposto
- Se estado == 'RJ': 20% de imposto
- Se estado == 'MG': 15% de imposto
- Outros: 17% de imposto

**Dica:** Use `np.where()`

In [34]:
vendas['imposto'] = np.where(vendas['estado'] == 'SP', 0.18, np.where(vendas['estado'] == 'RJ', 0.20, np.where(vendas['estado'] == 'MG', 0.15, 0.17)))

In [35]:
display(vendas)

,id,email,telefone,valor,valor_compra,estado,imposto
0,1,cliente1@email.com,21999990001.0,100.0,100,SP,0.18
1,2,cliente2@email.com,telefone não cadastrado,200.0,200,RJ,0.20
2,3,email não cadastrado,21999990003.0,150.0,150,MG,0.15
3,4,cliente4@email.com,telefone não cadastrado,300.0,300,SP,0.18
4,5,cliente5@email.com,21999990005.0,250.0,250,RJ,0.20
5,6,cliente6@email.com,telefone não cadastrado,180.0,180,MG,0.15
6,7,cliente7@email.com,telefone não cadastrado,220.0,220,ES,0.17
7,8,cliente8@email.com,21999990008.0,130.0,130,SP,0.18
8,9,email não cadastrado,21999990009.0,170.0,170,RJ,0.20
9,10,cliente10@email.com,telefone não cadastrado,190.0,190,MG,0.15

**EXERCICIO 5**

### Exercício 5: Identificar e Corrigir Atípicos ⭐⭐ 

**Enunciado:**
Coluna 'idade' tem valores: `[25, 35, 1500, 28, 0, 42, -5, 50]` (há erros)

Corrija usando `np.where()`:
- Se idade < 18 ou > 100: marque como 'Inválido'
- Senão: mantenha o valor

Depois, remova as inválidas.

**Dica:**

```phyton
    df = pd.DataFrame({'idade': [25, 35, 1500, 28, 0, 42, -5, 50]})
```

In [9]:
df = pd.DataFrame({'idade': [25, 35, 1500, 28, 0, 42, -5, 50]})
display(df)

   idade
0     25
1     35
2   1500
3     28
4      0
5     42
6     -5
7     50

In [10]:
df['idade_corrigida'] = np.where(
    (df['idade']<18) | (df['idade']>100), 
    'inválido', 
    df['idade']
    )
display(df)

   idade idade_corrigida
0     25              25
1     35              35
2   1500        inválido
3     28              28
4      0        inválido
5     42              42
6     -5        inválido
7     50              50

In [11]:
df_corrigido = df[df['idade_corrigida'] != 'inválido'].reset_index()
display(df_corrigido)

   index  idade idade_corrigida
0      0     25              25
1      1     35              35
2      3     28              28
3      5     42              42
4      7     50              50

In [12]:
df_novo = df_corrigido.drop(columns='idade_corrigida')
df_novo = df_novo.drop(columns='index')
display(df_novo)

   idade
0     25
1     35
2     28
3     42
4     50