## ✏️ Exercícios de Fixação

In [35]:
import pandas as pd
import numpy as np

**EXERCICIO 1**

**Enunciado:** Você tem os dados de aprovação de alunos em dois semestres:

```python
sem1 = pd.DataFrame({
    'aluno'      : ['Ana', 'Bruno', 'Carla'],
    'nota_media' : [7.8, 6.5, 9.2],
    'semestre'   : [1, 1, 1]
})

sem2 = pd.DataFrame({
    'aluno'      : ['Ana', 'Bruno', 'Diego'],
    'nota_media' : [8.1, 7.0, 6.8],
    'semestre'   : [2, 2, 2]
})
```

a) Use `pd.concat()` com `axis=0` para juntar os dois semestres em uma tabela única. Use `ignore_index=True`.  
b) Quantas linhas tem a tabela final? Confirme com `.shape`.

> 💡 **Dica:** Passe os DataFrames como uma lista: `pd.concat([sem1, sem2], ...)`.

In [36]:
sem1 = pd.DataFrame({
    'aluno'      : ['Ana', 'Bruno', 'Carla'],
    'nota_media' : [7.8, 6.5, 9.2],
    'semestre'   : [1, 1, 1]
})

sem2 = pd.DataFrame({
    'aluno'      : ['Ana', 'Bruno', 'Diego'],
    'nota_media' : [8.1, 7.0, 6.8],
    'semestre'   : [2, 2, 2]
})

In [37]:
nota_ano = pd.concat([sem1, sem2], axis=0, ignore_index=True)
display(nota_ano)

   aluno  nota_media  semestre
0    Ana         7.8         1
1  Bruno         6.5         1
2  Carla         9.2         1
3    Ana         8.1         2
4  Bruno         7.0         2
5  Diego         6.8         2

In [38]:
print(nota_ano.shape)

(6, 3)

**EXERCICIO 2**

**Enunciado:** Dado um sistema de RH com duas tabelas:

```python
funcionarios = pd.DataFrame({
    'id_func'  : [1, 2, 3, 4],
    'nome'     : ['Ana', 'Bruno', 'Carla', 'Diego'],
    'id_depto' : [10, 20, 10, 30]
})

departamentos = pd.DataFrame({
    'id_depto'  : [10, 20, 40],    # Depto 30 não existe; Depto 40 não tem funcionário
    'nome_depto': ['TI', 'RH', 'Marketing']
})
```

a) Faça um **inner join** para trazer o nome do departamento para a tabela de funcionários.  
b) Faça um **left join** e explique por que Diego aparece com `NaN` no departamento.

> 💡 **Dica:** A chave é `id_depto`. Use `how='inner'` e `how='left'` separadamente.

In [39]:
funcionarios = pd.DataFrame({
    'id_func'  : [1, 2, 3, 4],
    'nome'     : ['Ana', 'Bruno', 'Carla', 'Diego'],
    'id_depto' : [10, 20, 10, 30]
})

departamentos = pd.DataFrame({
    'id_depto'  : [10, 20, 40],    # Depto 30 não existe; Depto 40 não tem funcionário
    'nome_depto': ['TI', 'RH', 'Marketing']
})

display(funcionarios)
print('========')
display(departamentos)

   id_func   nome  id_depto
0        1    Ana        10
1        2  Bruno        20
2        3  Carla        10
3        4  Diego        30

========

   id_depto nome_depto
0        10         TI
1        20         RH
2        40  Marketing

In [40]:
empresa = pd.merge(funcionarios, departamentos, on='id_depto', how='inner')
display(empresa)

   id_func   nome  id_depto nome_depto
0        1    Ana        10         TI
1        2  Bruno        20         RH
2        3  Carla        10         TI

In [41]:
empresa_left = pd.merge(funcionarios, departamentos, on="id_depto", how='left')
display(empresa_left)

   id_func   nome  id_depto nome_depto
0        1    Ana        10         TI
1        2  Bruno        20         RH
2        3  Carla        10         TI
3        4  Diego        30        NaN

**EXERCICIO 3**

**Enunciado:** Uma empresa de delivery registrou os pedidos do mês:

```python
pedidos = pd.DataFrame({
    'id'        : range(1, 11),
    'cidade'    : ['SP','RJ','SP','BH','RJ','SP','BH','RJ','SP','BH'],
    'categoria' : ['Pizza','Sushi','Pizza','Hambúrguer','Sushi',
                   'Hambúrguer','Pizza','Hambúrguer','Sushi','Sushi'],
    'valor'     : [45.0, 89.0, 52.0, 38.0, 95.0, 42.0, 61.0, 35.0, 78.0, 55.0],
    'avaliacao' : [4.5, 5.0, 4.0, 3.8, 4.9, 4.2, 4.7, 3.5, 4.8, 4.6]
})
```

Responda **sem usar laços `for`**:

1. Qual é o valor total de pedidos por cidade?
2. Qual é a média de avaliação por categoria de comida?
3. Crie um resumo por cidade com: total de pedidos (`count`), valor total (`sum`) e avaliação média (`mean`). Use `.agg()` com um dicionário.

> 💡 **Dica:** Para o item 3, use `groupby('cidade').agg({'id': 'count', 'valor': 'sum', 'avaliacao': 'mean'})`.

In [42]:
pedidos = pd.DataFrame({
    'id'        : range(1, 11),
    'cidade'    : ['SP','RJ','SP','BH','RJ','SP','BH','RJ','SP','BH'],
    'categoria' : ['Pizza','Sushi','Pizza','Hambúrguer','Sushi',
                   'Hambúrguer','Pizza','Hambúrguer','Sushi','Sushi'],
    'valor'     : [45.0, 89.0, 52.0, 38.0, 95.0, 42.0, 61.0, 35.0, 78.0, 55.0],
    'avaliacao' : [4.5, 5.0, 4.0, 3.8, 4.9, 4.2, 4.7, 3.5, 4.8, 4.6]
})

display(pedidos)

   id cidade   categoria  valor  avaliacao
0   1     SP       Pizza   45.0        4.5
1   2     RJ       Sushi   89.0        5.0
2   3     SP       Pizza   52.0        4.0
3   4     BH  Hambúrguer   38.0        3.8
4   5     RJ       Sushi   95.0        4.9
5   6     SP  Hambúrguer   42.0        4.2
6   7     BH       Pizza   61.0        4.7
7   8     RJ  Hambúrguer   35.0        3.5
8   9     SP       Sushi   78.0        4.8
9  10     BH       Sushi   55.0        4.6

In [43]:
total_cidade = pedidos.groupby('cidade')['valor'].sum()
display(total_cidade)

cidade
BH    154.0
RJ    219.0
SP    217.0
Name: valor, dtype: float64

In [44]:
media_avaliacao = pedidos.groupby('categoria')['avaliacao'].mean().round(2)
display(media_avaliacao)

categoria
Hambúrguer    3.83
Pizza         4.40
Sushi         4.82
Name: avaliacao, dtype: float64

In [45]:
resumo = pedidos.groupby('cidade').agg({
    'id': 'count',
    'valor': 'sum',
    'avaliacao': 'mean'
})

display(resumo)

        id  valor  avaliacao
cidade
BH       3  154.0   4.366667
RJ       3  219.0   4.466667
SP       4  217.0   4.375000

**EXERCICIO 4**

**Enunciado:** Uma escola registrou as notas bimestrais de seus alunos:

```python
notas_raw = pd.DataFrame({
    'aluno'    : ['Ana','Ana','Ana','Ana','Bruno','Bruno','Bruno','Bruno'],
    'bimestre' : ['1B','2B','3B','4B','1B','2B','3B','4B'],
    'nota'     : [8.5, 7.0, 9.2, 8.8, 6.5, 7.5, 8.0, 7.2]
})
```

a) Crie uma `pivot_table` onde as linhas são os alunos, as colunas são os bimestres e os valores são as notas. Use `aggfunc='mean'`.  
b) Adicione uma coluna `media_anual` à tabela pivotada calculando a média de cada linha.  
c) Use `melt()` para reverter a tabela pivotada (sem a coluna `media_anual`) de volta ao formato longo.

> 💡 **Dica:** Para o item (b), use `tabela_pivot['media_anual'] = tabela_pivot.mean(axis=1)`. Para o (c), primeiro faça `reset_index()` antes do `melt()`.

In [46]:
#criação do data frame

notas_raw = pd.DataFrame({
    'aluno'    : ['Ana','Ana','Ana','Ana','Bruno','Bruno','Bruno','Bruno'],
    'bimestre' : ['1B','2B','3B','4B','1B','2B','3B','4B'],
    'nota'     : [8.5, 7.0, 9.2, 8.8, 6.5, 7.5, 8.0, 7.2]
})
display(notas_raw)

   aluno bimestre  nota
0    Ana       1B   8.5
1    Ana       2B   7.0
2    Ana       3B   9.2
3    Ana       4B   8.8
4  Bruno       1B   6.5
5  Bruno       2B   7.5
6  Bruno       3B   8.0
7  Bruno       4B   7.2

In [47]:
# item a.

notas_pivot = pd.pivot_table(
    notas_raw,
    values = 'nota',
    index = 'aluno',
    columns = 'bimestre',
    aggfunc = 'mean',
    fill_value = 0
).reset_index()
display(notas_pivot)

bimestre  aluno   1B   2B   3B   4B
0           Ana  8.5  7.0  9.2  8.8
1         Bruno  6.5  7.5  8.0  7.2

In [ ]:
# item b.

notas_pivot['media_anual'] = notas_pivot[['1B', '2B', '3B', '4B']].mean(axis=1).round(1)
display(notas_pivot)

''' somente quando todas as colunas são numéricas
notas_pivot['media_anual'] = notas_pivot.mean(axis=1).round(1)
display(notas_pivot)
'''

bimestre  aluno   1B   2B   3B   4B  media_anual
0           Ana  8.5  7.0  9.2  8.8          8.4
1         Bruno  6.5  7.5  8.0  7.2          7.3

In [ ]:
# item c. parte 1

notas_pivot = notas_pivot.drop('media_anual', axis=1)
display(notas_pivot)

bimestre   1B   2B   3B   4B
aluno
Ana       8.5  7.0  9.2  8.8
Bruno     6.5  7.5  8.0  7.2

In [51]:
#item c. parte 2

notas_pivot = notas_pivot.reset_index()
display(notas_pivot)

notas_melt = pd.melt(
    notas_pivot,
    id_vars = 'aluno',
    value_vars = ['1B', '2B', '3B', '4B'],
    var_name = 'bimestre',
    value_name = 'nota'
)
display(notas_melt)

bimestre  index  aluno   1B   2B   3B   4B  media_anual
0             0    Ana  8.5  7.0  9.2  8.8          8.4
1             1  Bruno  6.5  7.5  8.0  7.2          7.3

   aluno bimestre  nota
0    Ana       1B   8.5
1  Bruno       1B   6.5
2    Ana       2B   7.0
3  Bruno       2B   7.5
4    Ana       3B   9.2
5  Bruno       3B   8.0
6    Ana       4B   8.8
7  Bruno       4B   7.2